package derive

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/glincker/stacklit/internal/schema"
)

// CompactMap generates a token-efficient navigation map (~250 tokens) from an Index.
// This replaces 3,000-8,000 tokens of agent exploration with a single static block.
func CompactMap(idx *schema.Index) string {
	var b strings.Builder

	// Line 1: project summary
	totalMods := len(idx.Modules)
	b.WriteString(fmt.Sprintf("%s | %s | %d modules | %s lines",
		idx.Project.Name,
		idx.Tech.PrimaryLanguage,
		totalMods,
		formatNumber(idx.Structure.TotalLines),
	))
	if len(idx.Tech.Frameworks) > 0 {
		b.WriteString(" | ")
		b.WriteString(strings.Join(idx.Tech.Frameworks, ", "))
	}
	b.WriteString("\n")

	// Line 2: entry, test, env summary
	var meta []string
	if len(idx.Structure.Entrypoints) > 0 {
		meta = append(meta, "entry: "+idx.Structure.Entrypoints[0])
	}
	if idx.Hints.TestCmd != "" {
		meta = append(meta, "test: "+idx.Hints.TestCmd)
	}
	if len(idx.Hints.EnvVars) > 0 {
		meta = append(meta, fmt.Sprintf("env: %s", strings.Join(idx.Hints.EnvVars, ", ")))
	}
	if len(meta) > 0 {
		b.WriteString(strings.Join(meta, " | "))
		b.WriteString("\n")
	}

	// Module map
	b.WriteString("\nmodules:\n")

	// Sort modules by name for stable output.
	names := make([]string, 0, len(idx.Modules))
	for name := range idx.Modules {
		names = append(names, name)
	}
	sort.Strings(names)

	// Find max module name length for alignment.
	maxLen := 0
	for _, name := range names {
		if len(name) > maxLen {
			maxLen = len(name)
		}
	}
	// Cap padding at 30 chars.
	if maxLen > 30 {
		maxLen = 30
	}

	for _, name := range names {
		mod := idx.Modules[name]
		line := formatModuleLine(name, mod, maxLen)
		b.WriteString(line)
		b.WriteString("\n")
	}

	// Hot files
	if len(idx.Git.HotFiles) > 0 {
		b.WriteString("\nhot: ")
		var hotParts []string
		limit := 3
		if len(idx.Git.HotFiles) < limit {
			limit = len(idx.Git.HotFiles)
		}
		for _, hf := range idx.Git.HotFiles[:limit] {
			hotParts = append(hotParts, fmt.Sprintf("%s (%d commits/90d)", hf.Path, hf.Commits90d))
		}
		b.WriteString(strings.Join(hotParts, ", "))
		b.WriteString("\n")
	}

	// Add feature hint
	if idx.Hints.AddFeature != "" {
		b.WriteString("add-feature: ")
		b.WriteString(idx.Hints.AddFeature)
		b.WriteString("\n")
	}

	// Do not touch
	if len(idx.Hints.DoNotTouch) > 0 {
		b.WriteString("do-not-touch: ")
		b.WriteString(strings.Join(idx.Hints.DoNotTouch, ", "))
		b.WriteString("\n")
	}

	return b.String()
}

// InjectableBlock wraps the compact map in markers for injection into config files.
func InjectableBlock(idx *schema.Index) string {
	var b strings.Builder
	b.WriteString("# codebase map (auto-generated by stacklit — do not edit below this line)\n")
	b.WriteString("# regenerate: stacklit derive -i stacklit.json\n")
	b.WriteString("#\n")

	// Prefix each line of the compact map with "# " for comment-style files,
	// but for markdown files (CLAUDE.md) we use a fenced block.
	b.WriteString("```\n")
	b.WriteString(CompactMap(idx))
	b.WriteString("```\n")
	b.WriteString("# end stacklit map\n")

	return b.String()
}

const startMarker = "# codebase map (auto-generated by stacklit"
const endMarker = "# end stacklit map"

// InjectIntoFile inserts or replaces the stacklit block in a file.
func InjectIntoFile(path string, block string) error {
	existing, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return err
	}

	content := string(existing)

	sIdx := strings.Index(content, startMarker)
	eIdx := strings.Index(content, endMarker)

	if sIdx >= 0 && eIdx >= 0 {
		eIdx += len(endMarker)
		if eIdx < len(content) && content[eIdx] == '\n' {
			eIdx++
		}
		content = content[:sIdx] + block + content[eIdx:]
	} else {
		if len(content) > 0 {
			if !strings.HasSuffix(content, "\n") {
				content += "\n"
			}
			if !strings.HasSuffix(content, "\n\n") {
				content += "\n"
			}
		}
		content += block
	}

	return os.WriteFile(path, []byte(content), 0644)
}

// formatModuleLine builds a single module line like:
//
//	internal/auth/    → jwt, session | depends: store, config
func formatModuleLine(name string, mod schema.ModuleInfo, padTo int) string {
	display := name
	if len(display) > padTo {
		display = display[:padTo]
	}
	padded := display + strings.Repeat(" ", padTo-len(display))

	// Purpose as brief descriptor.
	purpose := strings.ToLower(mod.Purpose)

	var parts []string
	parts = append(parts, purpose)

	// Dependencies (abbreviated).
	if len(mod.DependsOn) > 0 {
		deps := abbreviateModules(mod.DependsOn)
		if len(deps) <= 4 {
			parts = append(parts, "depends: "+strings.Join(deps, ", "))
		}
	}

	// Depended-by if this is a critical module.
	if len(mod.DependedBy) >= 3 {
		depBy := abbreviateModules(mod.DependedBy)
		if len(depBy) <= 4 {
			parts = append(parts, "depended-by: "+strings.Join(depBy, ", "))
		}
	}

	return fmt.Sprintf("  %s  %s", padded, strings.Join(parts, " | "))
}

// abbreviateModules returns just the base name of each module path.
func abbreviateModules(mods []string) []string {
	out := make([]string, len(mods))
	for i, m := range mods {
		out[i] = filepath.Base(m)
	}
	return out
}

// formatNumber formats an integer with comma separators.
func formatNumber(n int) string {
	if n < 1000 {
		return fmt.Sprintf("%d", n)
	}
	if n < 1000000 {
		return fmt.Sprintf("%d,%03d", n/1000, n%1000)
	}
	return fmt.Sprintf("%d,%03d,%03d", n/1000000, (n/1000)%1000, n%1000)
}
